### ISSUE TITLE
multiple browsers

### ISSUE THREAD

**Issue by create3000** [andreasplesch/cobweb_dom#27]
Have tested the master version of cobwe_dom with the example from http://www.create3000.de/titania/download/ which uses multple X3DCanvas elements within the dom, but it does not work.

I get the following error on line 27:

TypeError: this.browser is undefined  cobweb_dom.js:21:27

**Comment by andreasplesch** [comment]
https://andreasplesch.github.io/cobweb_dom/tests/cobweb_multiview.xhtml

still works. Perhaps the cycle script somehow interferes?

**Comment by andreasplesch** [comment]
I could reproduce here:
https://rawgit.com/andreasplesch/cobweb_dom/a4d632cfe0681360924828f16a12ecab9ea3737a/tests/cycle.xhtml
I think it has to do how cycle is loaded before cobweb_dom which has to wait for cobweb.

**Comment by andreasplesch** [comment]
X3D.getBrowser(element) does not return a browser in cycle.xhtml but it does on multiview.xhtml

**Comment by andreasplesch** [comment]
Somehow the X3D callback is called before browsers were created.

**Comment by andreasplesch** [comment]
https://rawgit.com/andreasplesch/cobweb_dom/d7a659e0b4b5a8be3f79e0a35c72280c2f6c2f60/tests/cycle.xhtml
has the cycle2 script disabled and it works here.

**Comment by andreasplesch** [comment]
http://kenwheeler.github.io/slick/ as slideshow works better:

https://rawgit.com/andreasplesch/cobweb_dom/2819cb108142f6d624632600d1c61a724982e8d2/tests/cycle.xhtml

**Comment by create3000** [comment]
It's with jQuery!

Works fine.

**Comment by andreasplesch** [comment]
yeah, somehow the cycle2 plugin interfered. I see you switched to slick and figured out the styling. Looks good.
