### ISSUE TITLE
New URLs for cobweb

### ISSUE THREAD

**Issue by create3000** [andreasplesch/cobweb_dom#28]
There are new URLs for cobweb. 

Tagged version:

`<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/create3000/cobweb/3.3/dist/cobweb.css"/> <script type="text/javascript" src="https://cdn.rawgit.com/create3000/cobweb/3.3/dist/cobweb.min.js"></script> 
`

Latest version:

`<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/create3000/cobweb/latest/dist/cobweb.css"/> <script type="text/javascript" src="https://cdn.rawgit.com/create3000/cobweb/latest/dist/cobweb.min.js"></script> 
`

For testing purposes you could use just 'rawgit.com' as host name.

Maybe this is interesting for cobweb_dom too.

1. You could create such version for cobweb_dom under https://github.com/andreasplesch/cobweb_dom.
2. Go to releases.
3. Draft a new release.

**Comment by andreasplesch** [comment]
Thanks. I updated the URLs for the examples.
